 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/analyses", type: :request do
  # Analysis. As you add validations to Analysis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Analysis.create! valid_attributes
      get analyses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      analysis = Analysis.create! valid_attributes
      get analysis_url(analysis)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_analysis_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      analysis = Analysis.create! valid_attributes
      get edit_analysis_url(analysis)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Analysis" do
        expect {
          post analyses_url, params: { analysis: valid_attributes }
        }.to change(Analysis, :count).by(1)
      end

      it "redirects to the created analysis" do
        post analyses_url, params: { analysis: valid_attributes }
        expect(response).to redirect_to(analysis_url(Analysis.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Analysis" do
        expect {
          post analyses_url, params: { analysis: invalid_attributes }
        }.to change(Analysis, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post analyses_url, params: { analysis: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested analysis" do
        analysis = Analysis.create! valid_attributes
        patch analysis_url(analysis), params: { analysis: new_attributes }
        analysis.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the analysis" do
        analysis = Analysis.create! valid_attributes
        patch analysis_url(analysis), params: { analysis: new_attributes }
        analysis.reload
        expect(response).to redirect_to(analysis_url(analysis))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        analysis = Analysis.create! valid_attributes
        patch analysis_url(analysis), params: { analysis: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested analysis" do
      analysis = Analysis.create! valid_attributes
      expect {
        delete analysis_url(analysis)
      }.to change(Analysis, :count).by(-1)
    end

    it "redirects to the analyses list" do
      analysis = Analysis.create! valid_attributes
      delete analysis_url(analysis)
      expect(response).to redirect_to(analyses_url)
    end
  end
end
